[package]
name = "kampfkarren/hoarcekat"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@*"
Rodux = "roblox/rodux@*"
RoactRodux = "roblox/roact-rodux@*"